package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 收藏夹表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Collector implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 收藏夹编�?. */
	private Integer collectorid;

	/** 加入时间. */
	private String collectortime;

	/** 商品编号. */
	private Integer goodsid;

	/** 收藏夹分类名�?. */
	private String collectorname;

	/** 用户编号. */
	private Integer userid;

	/**
	 * 僐儞僗僩儔僋�?.
	 */
	public Collector() {
	}

	/**
	 * 收藏夹编�? 傪愝掕偟傑偡.
	 * 
	 * @param collectorid
	 *            收藏夹编�?
	 */
	public void setCollectorid(Integer collectorid) {
		this.collectorid = collectorid;
	}

	/**
	 * 收藏夹编�? 傪庢摼偟傑偡.
	 * 
	 * @return 收藏夹编�?
	 */
	public Integer getCollectorid() {
		return this.collectorid;
	}

	/**
	 * 加入时间 傪愝掕偟傑偡.
	 * 
	 * @param collectortime
	 *            加入时间
	 */
	public void setCollectortime(String collectortime) {
		this.collectortime = collectortime;
	}

	/**
	 * 加入时间 傪庢摼偟傑偡.
	 * 
	 * @return 加入时间
	 */
	public String getCollectortime() {
		return this.collectortime;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * 收藏夹分类名�? 傪愝掕偟傑偡.
	 * 
	 * @param collectorname
	 *            收藏夹分类名�?
	 */
	public void setCollectorname(String collectorname) {
		this.collectorname = collectorname;
	}

	/**
	 * 收藏夹分类名�? 傪庢摼偟傑偡.
	 * 
	 * @return 收藏夹分类名�?
	 */
	public String getCollectorname() {
		return this.collectorname;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((collectorid == null) ? 0 : collectorid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Collector other = (Collector) obj;
		if (collectorid == null) {
			if (other.collectorid != null) {
				return false;
			}
		} else if (!collectorid.equals(other.collectorid)) {
			return false;
		}

		return true;
	}

}
