package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 鍟嗗搧淇℃伅琛� 鍎屽儴鍎栧儖鍎斿�?.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Goods implements Serializable {

	@Override
	public String toString() {
		return "Goods [goodsid=" + goodsid + ", goodsname=" + goodsname
				+ ", brandname=" + brandname + ", price=" + price
				+ ", goodsnumber=" + goodsnumber + ", goodspicture="
				+ goodspicture + "]";
	}

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 鍟嗗搧缂栧彿. */
	private Integer goodsid;

	/** 鍟嗗搧鍚嶇�?. */
	private String goodsname;

	/** 鍝佺墝鍚�?. */
	private String brandname;

	/** 鍟嗗搧浠锋牸. */
	private Double price;

	/** 鍟嗗搧鏁伴噺. */
	private Double goodsnumber;

	/** 鍟嗗搧鍥剧墖. */
	private String goodspicture;

	/**
	 * 鍍愬劄鍍�?儵鍎斿儖鍍�.
	 */
	public Goods() {
	}

	/**
	 * 鍟嗗搧缂栧彿 鍌劃鎺曞仧鍌戝�?.
	 * 
	 * @param goodsid
	 *            鍟嗗搧缂栧彿
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 鍟嗗搧缂栧彿 鍌孩鎽煎仧鍌戝�?.
	 * 
	 * @return 鍟嗗搧缂栧彿
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * 鍟嗗搧鍚嶇�? 鍌劃鎺曞仧鍌戝�?.
	 * 
	 * @param goodsname
	 *            鍟嗗搧鍚嶇�?
	 */
	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	/**
	 * 鍟嗗搧鍚嶇�? 鍌孩鎽煎仧鍌戝�?.
	 * 
	 * @return 鍟嗗搧鍚嶇�?
	 */
	public String getGoodsname() {
		return this.goodsname;
	}

	/**
	 * 鍝佺墝鍚�? 鍌劃鎺曞仧鍌戝�?.
	 * 
	 * @param brandname
	 *            鍝佺墝鍚�?
	 */
	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	/**
	 * 鍝佺墝鍚�? 鍌孩鎽煎仧鍌戝�?.
	 * 
	 * @return 鍝佺墝鍚�?
	 */
	public String getBrandname() {
		return this.brandname;
	}

	/**
	 * 鍟嗗搧浠锋牸 鍌劃鎺曞仧鍌戝�?.
	 * 
	 * @param price
	 *            鍟嗗搧浠锋牸
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * 鍟嗗搧浠锋牸 鍌孩鎽煎仧鍌戝�?.
	 * 
	 * @return 鍟嗗搧浠锋牸
	 */
	public Double getPrice() {
		return this.price;
	}

	/**
	 * 鍟嗗搧鏁伴噺 鍌劃鎺曞仧鍌戝�?.
	 * 
	 * @param goodsnumber
	 *            鍟嗗搧鏁伴噺
	 */
	public void setGoodsnumber(Double goodsnumber) {
		this.goodsnumber = goodsnumber;
	}

	/**
	 * 鍟嗗搧鏁伴噺 鍌孩鎽煎仧鍌戝�?.
	 * 
	 * @return 鍟嗗搧鏁伴噺
	 */
	public Double getGoodsnumber() {
		return this.goodsnumber;
	}

	/**
	 * 鍟嗗搧鍥剧墖 鍌劃鎺曞仧鍌戝�?.
	 * 
	 * @param goodspicture
	 *            鍟嗗搧鍥剧墖
	 */
	public void setGoodspicture(String goodspicture) {
		this.goodspicture = goodspicture;
	}

	/**
	 * 鍟嗗搧鍥剧墖 鍌孩鎽煎仧鍌戝�?.
	 * 
	 * @return 鍟嗗搧鍥剧墖
	 */
	public String getGoodspicture() {
		return this.goodspicture;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((goodsid == null) ? 0 : goodsid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Goods other = (Goods) obj;
		if (goodsid == null) {
			if (other.goodsid != null) {
				return false;
			}
		} else if (!goodsid.equals(other.goodsid)) {
			return false;
		}

		return true;
	}

}
