package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 订单�? 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Orders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 订单编号. */
	private Integer orderid;

	/** 订单时间. */
	private String ordertime;

	/** 用户编号. */
	private Integer userid;

	/** 订单状�??. */
	private String orderstate;

	@Override
	public String toString() {
		return "Orders [orderid=" + orderid + ", ordertime=" + ordertime
				+ ", userid=" + userid + ", orderstate=" + orderstate
				+ ", orderaddress=" + orderaddress + ", something=" + something
				+ ", name=" + name + "]";
	}

	/** 收货地址. */
	private String orderaddress;

	/** 订单备注. */
	private String something;

	/** 用户名字. */
	private String name;

	/**
	 * 僐儞僗僩儔僋�?.
	 */
	public Orders() {
	}

	/**
	 * 订单编号 傪愝掕偟傑偡.
	 * 
	 * @param orderid
	 *            订单编号
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	/**
	 * 订单编号 傪庢摼偟傑偡.
	 * 
	 * @return 订单编号
	 */
	public Integer getOrderid() {
		return this.orderid;
	}

	/**
	 * 订单时间 傪愝掕偟傑偡.
	 * 
	 * @param ordertime
	 *            订单时间
	 */
	public void setOrdertime(String ordertime) {
		this.ordertime = ordertime;
	}

	/**
	 * 订单时间 傪庢摼偟傑偡.
	 * 
	 * @return 订单时间
	 */
	public String getOrdertime() {
		return this.ordertime;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * 订单状�?? 傪愝掕偟傑偡.
	 * 
	 * @param orderstate
	 *            订单状�??
	 */
	public void setOrderstate(String orderstate) {
		this.orderstate = orderstate;
	}

	/**
	 * 订单状�?? 傪庢摼偟傑偡.
	 * 
	 * @return 订单状�??
	 */
	public String getOrderstate() {
		return this.orderstate;
	}

	/**
	 * 收货地址 傪愝掕偟傑偡.
	 * 
	 * @param orderaddress
	 *            收货地址
	 */
	public void setOrderaddress(String orderaddress) {
		this.orderaddress = orderaddress;
	}

	/**
	 * 收货地址 傪庢摼偟傑偡.
	 * 
	 * @return 收货地址
	 */
	public String getOrderaddress() {
		return this.orderaddress;
	}

	/**
	 * 订单备注 傪愝掕偟傑偡.
	 * 
	 * @param something
	 *            订单备注
	 */
	public void setSomething(String something) {
		this.something = something;
	}

	/**
	 * 订单备注 傪庢摼偟傑偡.
	 * 
	 * @return 订单备注
	 */
	public String getSomething() {
		return this.something;
	}

	/**
	 * 用户名字 傪愝掕偟傑偡.
	 * 
	 * @param name
	 *            用户名字
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * 用户名字 傪庢摼偟傑偡.
	 * 
	 * @return 用户名字
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orderid == null) ? 0 : orderid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Orders other = (Orders) obj;
		if (orderid == null) {
			if (other.orderid != null) {
				return false;
			}
		} else if (!orderid.equals(other.orderid)) {
			return false;
		}

		return true;
	}

}
