package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 购物�? 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Shopcar implements Serializable {

	@Override
	public String toString() {
		return "Shopcar [id=" + id + ", goodsid=" + goodsid + ", number="
				+ number + ", shopgoodsid=" + shopgoodsid + "]";
	}

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 购物车id. */
	private Integer id;

	/** 商品编号. */
	private Integer goodsid;

	/** 购物车数�?. */
	private Integer number;

	/** 用户编号. */
	private Integer shopgoodsid;

	/**
	 * 僐儞僗僩儔僋�?.
	 */
	public Shopcar() {
	}

	/**
	 * 购物车id 傪愝掕偟傑偡.
	 * 
	 * @param id
	 *            购物车id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * 购物车id 傪庢摼偟傑偡.
	 * 
	 * @return 购物车id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goodsid
	 *            商品编号
	 */
	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGoodsid() {
		return this.goodsid;
	}

	/**
	 * 购物车数�? 傪愝掕偟傑偡.
	 * 
	 * @param number
	 *            购物车数�?
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * 购物车数�? 傪庢摼偟傑偡.
	 * 
	 * @return 购物车数�?
	 */
	public Integer getNumber() {
		return this.number;
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param shopgoodsid
	 *            用户编号
	 */
	public void setShopgoodsid(Integer shopgoodsid) {
		this.shopgoodsid = shopgoodsid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getShopgoodsid() {
		return this.shopgoodsid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Shopcar other = (Shopcar) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}

		return true;
	}

}
