package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 用户信息�? 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户编号. */
	private Integer userid;

	/** 用户�?. */
	private String username;

	/** 用户密码. */
	private String password;

	/** 用户昵称. */
	private String nickname;

	/** 用户头像. */
	private String picture;

	/** 用户性别. */
	private String sex;

	/** 用户年龄. */
	private Integer age;

	/** 用户电话号码. */
	private String tel;

	/**
	 * 僐儞僗僩儔僋�?.
	 */
	public Users() {
	}

	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param userid
	 *            用户编号
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * 用户�? 傪愝掕偟傑偡.
	 * 
	 * @param username
	 *            用户�?
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * 用户�? 傪庢摼偟傑偡.
	 * 
	 * @return 用户�?
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * 用户密码 傪愝掕偟傑偡.
	 * 
	 * @param password
	 *            用户密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * 用户密码 傪庢摼偟傑偡.
	 * 
	 * @return 用户密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * 用户昵称 傪愝掕偟傑偡.
	 * 
	 * @param nickname
	 *            用户昵称
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * 用户昵称 傪庢摼偟傑偡.
	 * 
	 * @return 用户昵称
	 */
	public String getNickname() {
		return this.nickname;
	}

	/**
	 * 用户头像 傪愝掕偟傑偡.
	 * 
	 * @param picture
	 *            用户头像
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * 用户头像 傪庢摼偟傑偡.
	 * 
	 * @return 用户头像
	 */
	public String getPicture() {
		return this.picture;
	}

	/**
	 * 用户性别 傪愝掕偟傑偡.
	 * 
	 * @param sex
	 *            用户性别
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * 用户性别 傪庢摼偟傑偡.
	 * 
	 * @return 用户性别
	 */
	public String getSex() {
		return this.sex;
	}

	/**
	 * 用户年龄 傪愝掕偟傑偡.
	 * 
	 * @param age
	 *            用户年龄
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * 用户年龄 傪庢摼偟傑偡.
	 * 
	 * @return 用户年龄
	 */
	public Integer getAge() {
		return this.age;
	}

	/**
	 * 用户电话号码 傪愝掕偟傑偡.
	 * 
	 * @param tel
	 *            用户电话号码
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * 用户电话号码 傪庢摼偟傑偡.
	 * 
	 * @return 用户电话号码
	 */
	public String getTel() {
		return this.tel;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Users other = (Users) obj;
		if (userid == null) {
			if (other.userid != null) {
				return false;
			}
		} else if (!userid.equals(other.userid)) {
			return false;
		}

		return true;
	}

}
