
/* Drop Tables */

DROP TABLE COLLECTOR;
DROP TABLE ORDERDETAILS;
DROP TABLE SHOPCAR;
DROP TABLE GOODS;
DROP TABLE ORDERS;
DROP TABLE USERS;




/* Create Tables */

CREATE TABLE COLLECTOR
(
	COLLECTORID INT NOT NULL AUTO_INCREMENT,
	COLLECTORTIME VARCHAR(20) NOT NULL,
	COLLECTORUSERID INT NOT NULL,
	COLLECTORNAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (COLLECTORID)
);


CREATE TABLE GOODS
(
	GOODSID INT NOT NULL AUTO_INCREMENT,
	GOODSNAME VARCHAR(20) NOT NULL,
	BRANDNAME VARCHAR(20) NOT NULL,
	PRICE DOUBLE NOT NULL,
	GOODSNUMBER DOUBLE NOT NULL,
	GOODSPICTURE VARCHAR(20) NOT NULL,
	PRIMARY KEY (GOODSID)
);


CREATE TABLE ORDERDETAILS
(
	ITEMID INT NOT NULL AUTO_INCREMENT,
	ORDERDETAILSGOODSID INT NOT NULL,
	ORDERDETAILSGOODSNUMBER DOUBLE NOT NULL,
	ORDERDETAILSORDERID INT NOT NULL,
	PRIMARY KEY (ITEMID)
);


CREATE TABLE ORDERS
(
	ORDERID INT NOT NULL AUTO_INCREMENT,
	ORDERTIME VARCHAR(20) NOT NULL,
	ORDERUSERID INT NOT NULL,
	ORDERSTATE VARCHAR(20) NOT NULL,
	ORDERADDRESS VARCHAR(20) NOT NULL,
	SOMETHING VARCHAR(50) NOT NULL,
	PRIMARY KEY (ORDERID)
);


CREATE TABLE SHOPCAR
(
	ID INT NOT NULL AUTO_INCREMENT,
	GOODSID INT NOT NULL,
	NUMBER INT NOT NULL,
	SHOPGOODSID INT NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE USERS
(
	USERID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(20) NOT NULL,
	PICTURE VARCHAR(20) NOT NULL,
	SEX VARCHAR(20) NOT NULL,
	AGE INT NOT NULL,
	TEL VARCHAR(20) NOT NULL,
	PRIMARY KEY (USERID)
);



/* Create Foreign Keys */

ALTER TABLE COLLECTOR
	ADD FOREIGN KEY (COLLECTORUSERID)
	REFERENCES GOODS (GOODSID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERDETAILS
	ADD FOREIGN KEY (ORDERDETAILSGOODSID)
	REFERENCES GOODS (GOODSID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SHOPCAR
	ADD FOREIGN KEY (GOODSID)
	REFERENCES GOODS (GOODSID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERDETAILS
	ADD FOREIGN KEY (ORDERDETAILSORDERID)
	REFERENCES ORDERS (ORDERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ORDERS
	ADD FOREIGN KEY (ORDERUSERID)
	REFERENCES USERS (USERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SHOPCAR
	ADD FOREIGN KEY (SHOPGOODSID)
	REFERENCES USERS (USERID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



